### PR TITLE
Move `lvl <= $crate::max_level()` inside called functions

### PR DESCRIPTION
**Pull request by EFanZh**
This change will reduce binary size at the cost of some performance loss.

### CODE REVIEW

**Comment by EFanZh** [comment]
I noticed a project I am working on has a decent size increase after upgrading the `log` crate dependency, it was cause by #446, but maybe there is a way to reduce the binary size impact of upgrading, so here is what I came up with. If the performance loss is unacceptable, how about using an option feature to provide this binary size over performance behavior?

**Comment by EFanZh** [comment]
Close as this will expand argument too early, causing behavior change.

**Comment by Thomasdezeeuw** [comment]
@EFanZh have you tried the log crate's filter features (https://docs.rs/log/latest/log/#compile-time-filters)? Those will help remove trace, debug (and more if desired) from the binary. It's also (part of) the reason why the if statement if outside of the function.

**Comment by EFanZh** [comment]
@Thomasdezeeuw Most of my logs are required to be printed, so disabling logs is not an option.

**Pull request closed without merging**
