### PR TITLE
Prepare for 0.4.21 release

### LINKED ISSUE #616: Release a build with `kv` support
Now that #613 is merged we have a "stable" API on the main branch that's ready to release. Before we do that, I'd like to run over any related projects we should look at and see whether there are any blocking API concerns (non-blocking additions in `log` for better support would be ok) we can discover at this last-responsible-moment.

Off the top of my head:

- [x] https://github.com/slog-rs/stdlog
- [x] https://github.com/tokio-rs/tracing/tree/master/tracing-log
- [x] https://github.com/open-telemetry/opentelemetry-rust/tree/main/opentelemetry-appender-log

Any others? This isn't a list of all projects that could use `log`'s structured logging support, just those that are likely to need substantial work to integrate and may reveal any design issues.

### PR DESCRIPTION
**Pull request by KodrAus**
cc @Thomasdezeeuw @JohnTitor This release stabilizes our structured logging API.

Closes #616 

## What's Changed
* Minor clippy nits by @nyurik in https://github.com/rust-lang/log/pull/578
* Simplify Display impl by @nyurik in https://github.com/rust-lang/log/pull/579
* Set all crates to 2021 edition by @nyurik in https://github.com/rust-lang/log/pull/580
* Various changes based on review by @Thomasdezeeuw in https://github.com/rust-lang/log/pull/583
* Fix typo in file_static() method doc by @dimo414 in https://github.com/rust-lang/log/pull/590
* Specialize empty key value pairs by @EFanZh in https://github.com/rust-lang/log/pull/576
* Fix incorrect lifetime in Value::to_str() by @peterjoel in https://github.com/rust-lang/log/pull/587
* Remove some API of the key-value feature by @Thomasdezeeuw in https://github.com/rust-lang/log/pull/585
* Add logcontrol-log and log-reload by @swsnr in https://github.com/rust-lang/log/pull/595
* Add Serialization section to kv::Value docs by @Thomasdezeeuw in https://github.com/rust-lang/log/pull/593
* Rename Value::to_str to to_cow_str by @Thomasdezeeuw in https://github.com/rust-lang/log/pull/592
* Clarify documentation and simplify initialization of `STATIC_MAX_LEVEL` by @ptosi in https://github.com/rust-lang/log/pull/594
* Update docs to 2021 edition, test by @nyurik in https://github.com/rust-lang/log/pull/577
* Add "alterable_logger" link to README.md by @brummer-simon in https://github.com/rust-lang/log/pull/589
* Normalize line ending by @EFanZh in https://github.com/rust-lang/log/pull/602
* Remove `ok_or` in favor of `Option::ok_or` by @AngelicosPhosphoros in https://github.com/rust-lang/log/pull/607
* Use `Acquire` ordering for initialization check by @AngelicosPhosphoros in https://github.com/rust-lang/log/pull/610
* Get structured logging API ready for stabilization by @KodrAus in https://github.com/rust-lang/log/pull/613

### CODE REVIEW

**Review by Thomasdezeeuw — APPROVED** [review]

**Comment by nyurik** [comment]
Should this be a minor change?  I think we need to add two lines to the CI workflow as described [here](https://github.com/obi1kenobi/cargo-semver-checks?tab=readme-ov-file#quick-start):

```yaml
- name: Check semver
  uses: obi1kenobi/cargo-semver-checks-action@v2
```

**Comment by nyurik** [comment]
I just added https://github.com/rust-lang/log/pull/618 - it might need to go in first to make sure we are not accidentally breaking semver contract

**Comment by nyurik** [comment]
P.S. yes, it is clearly failing, possibly due to the current Cargo.toml having the same version as the published one.  It seems patch version bump is not enough though.

My practice with that checker is that the version in the github main branch should be changed as soon as the breaking change is introduced. So either keep it as `0.5.0-pre.1` or as `0.5.0`, but in either case it must not be `0.4.20` after the release and after the breaking changes are merged.

**Comment by Thomasdezeeuw** [comment]
> Should this be a minor change?

What breaking changes do we have?

> I think we need to add two lines to the CI workflow as described [here](https://github.com/obi1kenobi/cargo-semver-checks?tab=readme-ov-file#quick-start):

Let's discuss this in the other pr.

**Comment by Thomasdezeeuw** [comment]
> @Thomasdezeeuw I see a bunch of the breaking changes in https://github.com/rust-lang/log/actions/runs/8072374937/job/22053982534?pr=618 -- do you think they are not correct?

Looking at that output. The as_map and as_list related stuff was removed on purpose.
Two things renamed: `Key::to_borrowed_str` -> `Key::as_str` and `Value::to_str` -> `Value::to_cow_str`.

So it LGTM, all the changes were part of the unstable API.

**Review by JohnTitor — APPROVED** [review]

**Comment by KodrAus** [comment]
Shipping this now :+1: I'll keep an eye on it over the next little while because releases with macro changes always come with risk.

**Comment by KodrAus** [comment]
@Thomasdezeeuw I've invited you to the organization I created where `value-bag` lives and will add you to the crate publishers too. Don't feel compelled to do anything if you're not interested (although you're very welcome to if you'd like!), but having permission to get builds and patches through there could be really useful someday.

**Pull request merged**
