### PR TITLE
Remove derived trait Hash as PartialEq is explicitly implemented

### PR DESCRIPTION
**Pull request by bpfoley**
Found by clippy
https://rust-lang.github.io/rust-clippy/master/#derive_hash_xor_eq

### CODE REVIEW

**Comment by sfackler** [comment]
We can't just not implement Hash anymore - that would break backwards compatibility. Our manual PartialEq impl is equivalent to what derive would generate.

**Comment by bpfoley** [comment]
Ah... So what's the best thing to do here? Add `#[allow(clippy::derive_hash_xor_eq)]`? Leave it alone?

**Comment by sfackler** [comment]
I'd probably just go with `#[allow(clippy::derive_hash_xor_eq)]`, yeah.

**Comment by thomaseizinger** [comment]
> Our manual PartialEq impl is equivalent to what derive would generate.

Out of curiosity: I saw that we do a cast to `usize` instead of just using the generated impl. What is the difference and consideration in terms of backwards compatibility?

**Comment by sfackler** [comment]
The derive-generated code was significantly larger and less efficient last time I checked. If that's no longer the case, we can derive them.

**Comment by KodrAus** [comment]
It's been over a year now so I'll go ahead and close this one. Thanks for investigating this though @thomaseizinger!

**Pull request closed without merging**
